// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdaUDW1X6dXZmODgafVML4-R7f3IHUSs',
    appId: '1:885119532349:web:2248c48c4c576358dc9954',
    messagingSenderId: '885119532349',
    projectId: 'flutter-clean-sneakers',
    authDomain: 'flutter-clean-sneakers.firebaseapp.com',
    storageBucket: 'flutter-clean-sneakers.firebasestorage.app',
    measurementId: 'G-0BVK02K1P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDbSY3EuIBq-_24aDssOiba5yqa6ZWNU',
    appId: '1:885119532349:android:aab63b7ad8fc4582dc9954',
    messagingSenderId: '885119532349',
    projectId: 'flutter-clean-sneakers',
    storageBucket: 'flutter-clean-sneakers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjdFqEVy4ISSvzKW_CFv1AachuBOnR3A',
    appId: '1:885119532349:ios:f980262f0c091797dc9954',
    messagingSenderId: '885119532349',
    projectId: 'flutter-clean-sneakers',
    storageBucket: 'flutter-clean-sneakers.firebasestorage.app',
    iosBundleId: 'com.toey.sneakers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnjdFqEVy4ISSvzKW_CFv1AachuBOnR3A',
    appId: '1:885119532349:ios:f980262f0c091797dc9954',
    messagingSenderId: '885119532349',
    projectId: 'flutter-clean-sneakers',
    storageBucket: 'flutter-clean-sneakers.firebasestorage.app',
    iosBundleId: 'com.toey.sneakers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkdaUDW1X6dXZmODgafVML4-R7f3IHUSs',
    appId: '1:885119532349:web:0a1a6280eab24ecedc9954',
    messagingSenderId: '885119532349',
    projectId: 'flutter-clean-sneakers',
    authDomain: 'flutter-clean-sneakers.firebaseapp.com',
    storageBucket: 'flutter-clean-sneakers.firebasestorage.app',
    measurementId: 'G-04BTX2GH3G',
  );
}
